server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888
      name: eureka-server
      profile: default
      label: main

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
