server:
  port: 8080

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      routes:
        - id: cotizacion
          uri: lb://microservice-cotizacion
          predicates:
            - Path=/api/v1/ordenes/**
        - id: impresoras
          uri: lb://microservice-impresoras
          predicates:
            - Path=/api/v1/impresoras/**
        - id: inventario
          uri: lb://microservice-inventario
          predicates:
            - Path=/api/v1/materiales/**
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
